Battleships::Player Class Reference
Represents a generic player in the Battleships game, managing their own board and guess logic.
#include <player.h>
Public Member Functions
Player (unsigned int size)
Construct a new Player object.
Board & getBoard ()
Get the Board object.
void applyGuess (Coord c)
Applies the guess at the cell at BOARD index (x,y) and changes its member variables accordingly.
std::vector< Ship > & getShips ()
Private Attributes
int ships_remaining
std::vector< Ship > ships
Board board
Detailed Description
Represents a generic player in the Battleships game, managing their own board and guess logic.
Constructor & Destructor Documentation
Player()
Player::Player (unsigned int size)
Construct a new Player object.
Parameters
size the size of the board
Member Function Documentation
applyGuess()
void Player::applyGuess (Coord c)
Applies the guess at the cell at BOARD index (x,y) and changes its member variables accordingly.
Parameters
x
y
References Battleships::Cell::getType(), Battleships::Cell::setGuessed(), and Battleships::Cell::setHit().
getBoard()
Board & Player::getBoard ()
Get the Board object.
Returns
Board&
The documentation for this class was generated from the following files:
include/model/player.h
src/model/player.cpp