Battleships::Cell Class Reference
Cell that makes up the board that can either be s ship, sea or border cell.
#include <cell.h>
Public Types
enum class CellType { SEA
, BOAT
, BORDER
 }
specifies the type of cell that determines the function of the cell.
Public Member Functions
std::string typeToString () const
Cell ()
Default constructor for Cell object.
Cell (CellType t)
Construct a new Cell object.
bool isHit () const
getter of hit
bool isGuessed () const
getter of guessed
CellType getType () const
Get the CellType.
void setGuessed (bool guess)
Set the Guessed object.
void setHit (bool hit)
Set the Hit object.
void setType (CellType t)
Set the Type object.
Private Attributes
bool guessed
bool hit
CellType type
Detailed Description
Cell that makes up the board that can either be s ship, sea or border cell.
Constructor & Destructor Documentation
Cell() [1/2]
Cell::Cell ()
Default constructor for Cell object.
Note
sets CellType::SEA by default unless specified.
References Cell().
Referenced by Cell().
Cell() [2/2]
Cell::Cell (CellType t)
Construct a new Cell object.
Parameters
t CellType of the cell
Member Function Documentation
getType()
Cell::CellType Cell::getType () const
Get the CellType.
Returns
CellType of the cell
Referenced by Battleships::Player::applyGuess().
isGuessed()
bool Cell::isGuessed () const
getter of guessed
Returns
true: if guessed through
false
isHit()
bool Cell::isHit () const
getter of hit
Returns
hit member.
Note
returns true if the cell has CellType::BOAT and is guessed.
setGuessed()
void Cell::setGuessed (bool guess)
Set the Guessed object.
Parameters
guess
Referenced by Battleships::Player::applyGuess().
setHit()
void Cell::setHit (bool hit)
Set the Hit object.
Parameters
hit
Referenced by Battleships::Player::applyGuess().
setType()
void Cell::setType (Cell::CellType t)
Set the Type object.
Parameters
t
The documentation for this class was generated from the following files:
include/model/cell.h
src/model/cell.cpp